### ISSUE TITLE
Update Issue/PR Templates

### ISSUE THREAD

**Issue by aakhtar3** [disneystreaming/automated-cloud-advisor#106]
Add new templates for Issues and PRs

## Pull Request

Would like placement for issue #

- [ ] [Pull Request](https://raw.githubusercontent.com/disneystreaming/automated-cloud-advisor/main/.github/PULL_REQUEST_TEMPLATE/pr)

## Issues

Make shorter but be able to identify bug and image reference.

- [ ] [Bug Report](https://raw.githubusercontent.com/disneystreaming/automated-cloud-advisor/main/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by priyanshupardhi** [comment]
Hey, @aakhtar3 Can you specify where to add the "template"?

**Comment by qwezii** [comment]
Hey
I could add Issue/PR templates. 
But what are the requirements?

And I think, to add an Issue template I would require the repo access.

Issue template: [link](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository)
PR template: [link](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

**Comment by aakhtar3** [comment]
In the .github directory, there should already be a few templates.

They are basic, but not ideal. It would be nice if they were simple and concise.

**Comment by Kevinpaulose05** [comment]
@aakhtar3  Can i propose a few templates? Will that count as a PR?

**Comment by aakhtar3** [comment]
I updated the issue with some more details.

**Comment by nobody5050** [comment]
really? 4 minutes late?! Lol
